apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  labels:
    app: admin-app
spec:
  selector:
    matchLabels:
      app: admin-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
      - image: ${IMAGE}
        name: admin-app
        env:
          - name: MYSQL_HOST
            value: paf-admin-mysql
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: mysql_database
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: mysql_password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: mysql_user
          - name: PORT
            value: '${SERVER_PORT}'
          - name: HOST
            value: 0.0.0.0
          - name: NODE_ENV
            value: production
          - name: APP_KEY
            value: ohLVdeSZ78VtWMSJtNN7kb5DkmCNxP91
          - name: APP_NAME
            value: PAF-admin
          - name: SESSION_DRIVER
            value: cookie
          - name: CACHE_VIEWS
            value: 'false'
          - name: DB_CONNECTION
            value: mysql
          - name: SPARKPOST_API_KEY
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: sparkpost_api_key
          - name: DROPBOX_USER
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: dropbox_user
          - name: DROPBOX_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: dropbox_password
          - name: DROPBOX_REFRESH_TOKEN
            valueFrom:
              configMapKeyRef:
                name: admin-app
                key: dropbox_refresh_token


        ports:
        - containerPort: ${SERVER_PORT}
          name: admin-app