import Route from '@ioc:Adonis/Core/Route'


// Route.post('migrate', 'MembersController.migrate').middleware('auth')

Route.route('/', ['HEAD'], 'AuthController.head').middleware('auth')
Route.post('login', 'AuthController.login')
Route.post('logout', 'AuthController.logout')
Route.get('users', 'AuthController.list').middleware('auth')
Route.post('user', 'AuthController.register').middleware('auth')
Route.delete('user/:id', 'AuthController.delete').middleware('auth')

Route.get('accounting/:year', 'StatsController.accounting').middleware('auth')

Route.post('bankrun', 'BankrunController.store').middleware('auth')
Route.put('bankrun/:id', 'BankrunController.update').middleware('auth')
Route.post('bankruns', 'BankrunController.paginatedList').middleware('auth')

Route.get('booking/:id', 'BookingsController.show').middleware('auth')
Route.get('bookings', 'BookingsController.list').middleware('auth')
Route.get('bookings/groups', 'BookingsController.listGroups').middleware('auth')
Route.get('bookings/reservations/:year?', 'BookingsController.reservations').middleware('auth')
Route.post('booking', 'BookingsController.store').middleware('auth')
Route.post('bookings', 'BookingsController.paginatedList').middleware('auth')
Route.post('bookings/byName', 'BookingsController.showByName').middleware('auth')
Route.post('bookings/byIds', 'BookingsController.showByIds').middleware('auth')
Route.post('bookings/stats', 'StatsController.stats').middleware('auth')
Route.put('booking/:id', 'BookingsController.update').middleware('auth')
Route.post('bookingPaid', 'BookingsController.updatePaidDate').middleware('auth')
Route.delete('booking/:id', 'BookingsController.delete').middleware('auth')

Route.get('event-calendar', 'EventsController.cal')

Route.post('data/bookings/', 'StatsController.bookinsgCsv').middleware('auth')
Route.post('data/invoices/', 'StatsController.invoicesCsv').middleware('auth')

Route.get('event/:id', 'EventsController.show').middleware('auth')
Route.get('events/', 'EventsController.list').middleware('auth')
Route.post('event', 'EventsController.store').middleware('auth')
Route.put('event/:id', 'EventsController.update').middleware('auth')
Route.delete('event/:id', 'EventsController.delete').middleware('auth')

Route.get('invoice/:id', 'InvoicesController.show').middleware('auth')
Route.get('invoices', 'InvoicesController.list').middleware('auth')
Route.get('invoiceNumbers', 'InvoicesController.listInvoiceNumbers').middleware('auth')
Route.get('invoicesBankRun', 'InvoicesController.listBankRun').middleware('auth')
Route.get('invoice/pdf/:id', 'ArchivesController.downloadInvoice').middleware('auth')
Route.post('invoice', 'InvoicesController.store').middleware('auth')
Route.post('invoices', 'InvoicesController.paginatedList').middleware('auth')
Route.post('invoicesBankRun', 'InvoicesController.listSelected').middleware('auth')
Route.post('invoices/reconciliation', 'InvoicesController.reconciliationList').middleware('auth')
Route.post('invoices/byName', 'InvoicesController.showByName').middleware('auth')
Route.post('invoices/byNumber', 'InvoicesController.showByNumber').middleware('auth')
Route.put('invoice/:id/:email', 'InvoicesController.update').middleware('auth')
Route.delete('invoice/:id', 'InvoicesController.delete').middleware('auth')
Route.post('invoice/archive', 'ArchivesController.invoice').middleware('auth')

Route.get('mattress/account', 'MattressesController.showAccounting').middleware('auth')
Route.get('mattress/allocated', 'MattressesController.showAllocatedNights').middleware('auth')
Route.get('mattress/income', 'MattressesController.showIncome').middleware('auth')
Route.get('mattress/names', 'MattressesController.names').middleware('auth')
Route.get('mattress/booking/:id', 'MattressesController.showByBookingId').middleware('auth')
Route.post('mattress', 'MattressesController.store').middleware('auth')
Route.post('mattress/list', 'MattressesController.paginatedList').middleware('auth')
Route.put('mattress/:id', 'MattressesController.update').middleware('auth')
Route.delete('mattress/:id', 'MattressesController.delete').middleware('auth')

Route.get('member/:id', 'MembersController.show').middleware('auth')
Route.get('member/pdf/:id', 'ArchivesController.downloadMembership').middleware('auth')
Route.get('members', 'MembersController.list').middleware('auth')
Route.get('memberEmails', 'MembersController.listMemberEmails').middleware('auth')
Route.post('newsletterEmails', 'MembersController.listNewsletterEmails').middleware('auth')
Route.post('members', 'MembersController.paginatedList').middleware('auth')
Route.post('member', 'MembersController.store').middleware('auth')
Route.post('members/byEmail', 'MembersController.showByEmail').middleware('auth')
Route.post('members/byName', 'MembersController.showByName').middleware('auth')
Route.get('members/sci', 'MembersController.listSci').middleware('auth')
Route.put('member/:id', 'MembersController.update').middleware('auth')
Route.delete('member/:id', 'MembersController.delete').middleware('auth')
Route.post('member/archive', 'ArchivesController.member').middleware('auth')
Route.post('member/pdf', 'PDFController.membership').middleware('auth')

Route.post('payments', 'BookingsController.paginatedPaymentList').middleware('auth')

Route.get('settings', 'SettingsController.list').middleware('auth')
Route.put('settings', 'SettingsController.update').middleware('auth')
